# Generated by Django 3.2.8 on 2021-10-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='тэг')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='WHEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название ивента')),
                ('source_link', models.CharField(max_length=200, verbose_name='Ссылка на ивент')),
                ('date_of_event', models.DateField(verbose_name='Дата проведения')),
                ('system', models.CharField(choices=[('40k', '40k'), ('AOS', 'AOS'), ('KT', 'Kill Team'), ('WC', 'WarCry')], max_length=100, verbose_name='Система по которой проходит турнир')),
                ('tags', models.ManyToManyField(to='events.Tag', verbose_name='Тэги ивента')),
            ],
            options={
                'verbose_name': 'Ивент',
                'verbose_name_plural': 'Ивенты',
            },
        ),
    ]
